name: build

on: push

permissions:
  contents: write

env:
  GENERATOR: Visual Studio 17 2022
  ARCH: Win32
  CONFIG: Release
  FILENAME: l2ui.dll
  BUILD_DIR: build

jobs:
  build-project:
    runs-on: windows-2022
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3.3.0

      - name: Configure project
        run: cmake . -B $env:BUILD_DIR -G $env:GENERATOR -A $env:ARCH

      - name: Build project
        run: cmake --build $env:BUILD_DIR --config $env:CONFIG

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./${{env.BUILD_DIR}}/${{env.CONFIG}}/${{env.FILENAME}}
